In [1]:
import numpy as np
import cv2

In [2]:
n = np.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [3]:
type(n)

numpy.ndarray

In [4]:
n.reshape(3, 9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [5]:
n.reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [11]:
img = cv2.imread('./smallgray.png', 0)
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [9]:
cv2.imwrite('smallgray2.png', img)

True

In [13]:
img[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [23]:
ims = np.hstack((img, img, img))

In [24]:
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [27]:
hsplit_list = np.hsplit(ims, 5)

In [29]:
print(hsplit_list)

[array([[187, 158, 104],
       [198, 125, 255],
       [209, 134, 255]], dtype=uint8), array([[121, 143, 187],
       [255, 147, 198],
       [ 97, 182, 209]], dtype=uint8), array([[158, 104, 121],
       [125, 255, 255],
       [134, 255,  97]], dtype=uint8), array([[143, 187, 158],
       [147, 198, 125],
       [182, 209, 134]], dtype=uint8), array([[104, 121, 143],
       [255, 255, 147],
       [255,  97, 182]], dtype=uint8)]
